**BIG BIG HINT! Look in the instructions to guide you on this task.**

In [7]:
# Dependencies
import pandas as pd

In [10]:
# load CSV
file="Resources/2016-FCC-New-Coders-Survey-Data.csv"

In [15]:
# Read with pandas
df= pd.read_csv(file)
df.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampMonthsAgo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,...,ResourceSoloLearn,ResourceStackOverflow,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3Schools,ResourceYouTube,SchoolDegree,SchoolMajor,StudentDebtOwe
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,20000.0
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"some college credit, no degree",NaN,NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high school diploma or equivalent (GED),NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bachelor's degree,Cinematography And Film,7000.0
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN

In [16]:
# Inspect all columns
df.columns

Index(['Age', 'AttendedBootcamp', 'BootcampFinish', 'BootcampFullJobAfter',
       'BootcampLoanYesNo', 'BootcampMonthsAgo', 'BootcampName',
       'BootcampPostSalary', 'BootcampRecommend', 'ChildrenNumber',
       ...
       'ResourceSoloLearn', 'ResourceStackOverflow', 'ResourceTreehouse',
       'ResourceUdacity', 'ResourceUdemy', 'ResourceW3Schools',
       'ResourceYouTube', 'SchoolDegree', 'SchoolMajor', 'StudentDebtOwe'],
      dtype='object', length=113)

In [34]:
# Extract only columns 0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111
df_reduced=df.iloc[:, [0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111]]
df_reduced.columns

Index(['Age', 'AttendedBootcamp', 'BootcampFinish', 'BootcampFullJobAfter',
       'BootcampLoanYesNo', 'BootcampPostSalary', 'BootcampRecommend',
       'ChildrenNumber', 'CityPopulation', 'CodeEventBootcamp', 'CountryLive',
       'EmploymentField', 'EmploymentStatus', 'Gender', 'HasChildren',
       'HoursLearning', 'Income', 'JobRoleInterest', 'SchoolDegree',
       'SchoolMajor'],
      dtype='object')

In [33]:
# Change "0" to "No" and "1" to "Yes" in response columns
df_reduced.replace({0:"No",1:"Yes"})

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,office and administrative support,Employed for wages,male,No,30,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,food and beverage,Employed for wages,male,NaN,30,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Employed for wages,male,NaN,20,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,education,Employed for wages,female,NaN,25,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN
5,34.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Self-employed freelancer,male,NaN,5,40000.0,NaN,bachelor's degree,English
6,23.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Singapore,software development,Employed for wages,male,NaN,8,32000.0,NaN,bachelor's degree,Computer Science
7,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United Kingdom,office and administrative support,Employed for wages,male,No,NaN,40000.0,NaN,master's degree (non-professional),Education
8,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,5,80000.0,NaN,bachelor's degree,Business Administration
9,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,NaN,Employed for wages,male,NaN,20,80000.0,NaN,master's degree (non-professional),Business Administration
10,57.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,United States of America,NaN,Self-employed business owner,male,No,8,20000.0,NaN,bachelor's degree,Computer Science
11,23.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Bangladesh,NaN,Not working and not looking for work,male,NaN,5,NaN,NaN,"some college credit, no degree",NaN
12,47.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Canada,health care,Employed for wages,male,NaN,5,90000.0,NaN,bachelor's degree,Mechanical Engineering
13,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,5,NaN,NaN,bachelor's degree,Business Administration
14,37.0,No,NaN,NaN,NaN,NaN,NaN,Yes,"between 100,000 and 1 million",NaN,Bosnia & Herzegovina,sales,Self-employed business owner,male,Yes,2,NaN,NaN,"some college credit, no degree",NaN
15,31.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Russia,software development,Employed for wages,female,NaN,10,NaN,NaN,"professional degree (MBA, MD, JD, etc.)",Math
16,27.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,software development,Employed for wages,female,NaN,4,80000.0,NaN,bachelor's degree,Economics
17,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,United States of America,education,Employed for wages,male,NaN,5,17000.0,NaN,bachelor's degree,Music
18,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Canada,software development,Self-employed freelancer,male,NaN,2,16000.0,NaN,bachelor's degree,Music
19,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,Croatia,NaN,Not working but looking for work,male,No,20,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
20,32.0,No,NaN,NaN,NaN,NaN,NaN,Yes,more than 1 million,NaN,United States of America,NaN,Employed for wages,female,Yes,5,200000.0,Full-Stack Web Developer,master's degree (non-professional),Geology
21,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Doing an unpaid internship,female,NaN,NaN,NaN,NaN,bachelor's degree,Computer Science
22,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,No,10,100000.0,NaN,bachelor's degree,Computer Science
23,44.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,office and administrative support,Employed for wages,female,No,30,41000.0,NaN,bachelor's degree,Political Science
24,21.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,NaN,Not working but looking for work,male,NaN,25,NaN,NaN,bachelor's degree,Computer Science
25,21.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working but looking for work,male,NaN,25,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
26,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,South Africa,NaN,Self-employed freelancer,male,No,Yes,12000.0,NaN,high school diploma or equivalent (GED),NaN
27,28.0,No,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,United States of America,software development,Employed for wages,male,Yes,10,60000.0,NaN,"trade, technical, or vocational training",NaN
28,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,10,75000.0,Full-Stack Web Developer,bachelor's degree,Political Science
29,35.0,No,NaN,NaN,NaN,NaN,NaN,Yes,"less than 100,000",NaN,United Kingdom,software development,Employed for wages,male,Yes,5,35000.0,NaN,master's degree (non-professional),Physics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15590,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,NaN,2,200000.0,NaN,bachelor's degree,Computer Science
15591,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Brazil,software development and IT,Employed for wages,male,No,2,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Computer Systems Networking and Telecommunicat...
15592,43.0,No,NaN,NaN,NaN,NaN,NaN,Yes,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,Yes,3,200000.0,NaN,high school diploma or equivalent (GED),NaN
15593,29.0,Yes,No,NaN,No,NaN,No,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,female,No,5,200000.0,NaN,bachelor's degree,Accounting
15594,36.0,No,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,United States of America,finance,Employed for wages,male,Yes,Yes,200000.0,NaN,bachelor's degree,Engineering
15595,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Ukraine,software development and IT,Self-employed freelancer,male,No,30,200000.0,NaN,some high school,NaN
15596,30.0,No,NaN,NaN,NaN,NaN,NaN,2,"less than 100,000",NaN,Brazil,software development and IT,Employed for wages,male,Yes,2,200000.0,NaN,high school diploma or equivalent (GED),NaN
15597,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Ukraine,legal,Self-employed freelancer,male,NaN,6,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Law
15598,28.0,No,NaN,NaN,NaN,NaN,NaN,Yes,"less than 100,000",NaN,United States of America,food and beverage,Employed for wages,male,Yes,20,200000.0,Full-Stack Web Developer,associate's degree,Computer and Information Systems Security
15599,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,NaN,5,200000.0,NaN,"some college credit, no degree",NaN
15600,28.0,Yes,Yes,Yes,No,36000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,female,NaN,8,200000.0,NaN,bachelor's degree,Marketing
15601,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,legal,Employed for wages,male,NaN,10,200000.0,NaN,bachelor's degree,Criminal Justice and Safety Studies
15602,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,India,software development and IT,Employed for wages,male,NaN,50,200000.0,Data Scientist / Data Engineer,bachelor's degree,Mathematics
15603,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,software development and IT,Employed for wages,male,NaN,4,200000.0,NaN,bachelor's degree,Computer Science
15604,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,Norway,construction and extraction,Employed for wages,male,NaN,5,200000.0,Front-End Web Developer,"some college credit, no degree",NaN
15605,31.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Portugal,software development and IT,Employed for wages,male,NaN,5,200000.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15606,43.0,No,NaN,NaN,NaN,NaN,NaN,3,more than 1 million,NaN,Canada,legal,Self-employed business owner,male,Yes,3,200000.0,NaN,bachelor's degree,Physics
15607,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Philippines,software development,Self-employed freelancer,male,No,8,200000.0,NaN,no high school (secondary school),NaN
15608,43.0,No,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,United States of America,health care,Employed for wages,male,Yes,6,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical Engineering
15609,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Mexico,software development and IT,Employed for wages,male,No,16,200000.0,NaN,bachelor's degree,Software Engineering
15610,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,education,Employed for wages,male,NaN,5,200000.0,Front-End Web Developer,master's degree (non-professional),Religious Studies
15611,37.0,No,NaN,NaN,NaN,NaN,NaN,Yes,more than 1 million,NaN,Canada,software development and IT,Self-employed business owner,male,Yes,40,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical and Electronics Engineering
15612,45.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Employed for wages,female,NaN,2,200000.0,NaN,"some college credit, no degree",NaN
15613,30.0,No,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,South Africa,software development and IT,Employed for wages,male,Yes,4,200000.0,NaN,"trade, technical, or vocational training",NaN
15614,47.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,finance,Employed for wages,male,NaN,3,26000.0,NaN,"trade, technical, or vocational training",NaN
15615,39.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Kenya,software development and IT,Self-employed freelancer,male,No,40,10000.0,NaN,bachelor's degree,Chemistry
15616,27.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,No,15,10000.0,Front-End Web Developer,bachelor's degree,Electrical Engineering
15617,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Nigeria,NaN,Self-employed freelancer,male,NaN,14,48000.0,NaN,bachelor's degree,Chemistry
15618,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Spain,education,Self-employed freelancer,male,NaN,10,10000.0,NaN,master's degree (non-professional),Math
15619,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,No,2,18000.0,NaN,bachelor's degree,Graphic Design

In [35]:
# Calculate total number of respondents in survey
df_reduced.count()

Age                     13613
AttendedBootcamp        15380
BootcampFinish            933
BootcampFullJobAfter      635
BootcampLoanYesNo         934
BootcampPostSalary        330
BootcampRecommend         937
ChildrenNumber           2554
CityPopulation          13630
CodeEventBootcamp          42
CountryLive             13610
EmploymentField          7608
EmploymentStatus        12904
Gender                  13746
HasChildren              4012
HoursLearning           14942
Income                   7329
JobRoleInterest          6503
SchoolDegree            13679
SchoolMajor              8450
dtype: int64

In [ ]:
# Extract rows corresponding only to people who attended a bootcamp

In [ ]:
# Calculate average age of attendees

# Calculate how many people attended a bootcamp

# Calculate how many attendees hold degrees

# Count number of attendees who self-identify as male; female; or are of non-binary gender identification

# Calculate percentage of respondents who attended a bootcamp

# Calculate percentage of respondents belonging to each gender

# Calculate percentage of attendees with a school degree

# Calculate average post-bootcamp salary

In [ ]:
# Create a new table consolodating above calculations

In [ ]:
# Improve formatting before outputting spreadsheet

In [ ]:
# Export to Excel